### ISSUE TITLE
WEC-Eng.zip: tokens_number incorrect for several mentions

### ISSUE THREAD

**Issue by mbugert** [AlonEirew/extract-wec#2]
Hi Alon,

just wanted to let you know that the `tokens_number` field is incorrect for several mentions in the `train` and `test` splits of WEC-ENG.zip. Below is a list of all mentions where the `mention_head` token is not part of the tokens referenced by `tokens_number` (i.e. `len([i for i in tokens_number if mention_context[i] == mention_head]) == 0`). It looks like a problem with sentence tokenization.

#### train
|   mention_id | tokens_str                             | tokens_number            | tokens_str_detokenized                 |
|--------------|----------------------------------------|--------------------------|----------------------------------------|
|        24667 | 22. July attacks in 2011               | [2, 3]                   | 22 .                                   |
|        69138 | 2019 Kerrang! Awards                   | [5, 6, 7]                | 2019 Kerrang !                         |
|        69139 | Kerrang! Awards                        | [7, 8]                   | Kerrang !                              |
|        69140 | Kerrang! Award                         | [130, 131]               | Kerrang !                              |
|        69142 | 2019 Kerrang! Awards                   | [62, 63, 64]             | 2019 Kerrang !                         |
|        69143 | Kerrang! Awards                        | [114, 115]               | Kerrang !                              |
|        69144 | Kerrang! Award                         | [6, 7]                   | Kerrang !                              |
|        69145 | 2019 Kerrang! Awards                   | [102, 103, 104]          | 2019 Kerrang !                         |
|        69146 | Kerrang! Awards                        | [16, 17]                 | Kerrang !                              |
|        69147 | Kerrang! Award                         | [244, 245]               | Kerrang !                              |
|        69148 | Kerrang! Award                         | [318, 319]               | Kerrang !                              |
|        69149 | 2019 Kerrang! Awards                   | [110, 111, 112]          | 2019 Kerrang !                         |
|        95589 | Tina!: 50th Anniversary Tour           | [48, 49]                 | Tina !                                 |
|        95592 | Tina!: 50th Anniversary Tour           | [6, 7]                   | Tina !                                 |
|        95601 | Tina!: 50th Anniversary Tour           | [142, 143]               | Tina !                                 |
|        95603 | Tina!: 50th Anniversary Tour           | [11, 12]                 | Tina !                                 |
|       105430 | Girl Power! Live in Istanbul           | [58, 59, 60]             | Girl Power !                           |
|       105432 | Girl Power! Live in Istanbul           | [102, 103, 104]          | Girl Power !                           |
|       105433 | Girl Power! Live in Istanbul           | [188, 189, 190]          | Girl Power !                           |
|       105436 | Girl Power! Live in Istanbul           | [61, 62, 63]             | Girl Power !                           |
|       112575 | Kerrang! Awards                        | [95, 96]                 | Kerrang !                              |
|       112576 | Kerrang! Awards 2012                   | [125, 126]               | Kerrang !                              |
|       112577 | Kerrang! Awards 2012                   | [232, 233]               | Kerrang !                              |
|       119763 | Radio Disney Live! 2001 World Tour     | [48, 49, 50, 51]         | Radio Disney Live !                    |
|       119764 | Radio Disney Live! 2001 World Tour     | [116, 117, 118, 119]     | Radio Disney Live !                    |
|       119948 | 2009 Premios Oye! Awards               | [429, 430, 431, 432]     | 2009 Premios Oye !                     |
|       124830 | Kerrang! Awards 2007                   | [47, 48]                 | Kerrang !                              |
|       124831 | Kerrang! Awards 2007                   | [144, 145]               | Kerrang !                              |

#### test
|   mention_id | tokens_str                   | tokens_number   | tokens_str_detokenized   |
|--------------|------------------------------|-----------------|--------------------------|
|       102441 | Oops!... I Did It Again Tour | [9, 10]         | Oops !                   |
|       102444 | Oops!... I Did It Again Tour | [725, 726]      | Oops !                   |
|       102445 | Oops!... I Did It Again Tour | [61, 62]        | Oops !                   |
|       102450 | Oops!... I Did It Again Tour | [8, 9]          | Oops !                   |

`tokens_str_detokenized` is the output of `" ".join(mention_context[i] for i in tokens_number)`.

**Comment by mbugert** [comment]
Quick fix for the mentions above; a mapping from `mention_id` to fixed `tokens_number`:
```python3
{
    "24667": [2, 3, 4, 5, 6, 7],
    "69138": [5, 6, 7, 8],
    "69139": [7, 8, 9],
    "69140": [130, 131, 132],
    "69142": [62, 63, 64, 65],
    "69143": [114, 115, 116],
    "69144": [6, 7, 8],
    "69145": [102, 103, 104, 105],
    "69146": [16, 17, 18],
    "69147": [244, 245, 246],
    "69148": [318, 319, 320],
    "69149": [110, 111, 112, 113],
    "95589": [48, 49, 50, 51, 52, 53],
    "95592": [6, 7, 8, 9, 10, 11],
    "95601": [142, 143, 144, 145, 146, 147],
    "95603": [11, 12, 13, 14, 15, 16],
    "105430": [58, 59, 60, 61, 62, 63],
    "105432": [102, 103, 104, 105, 106, 107],
    "105433": [188, 189, 190, 191, 192, 193],
    "105436": [61, 62, 63, 64, 65, 66],
    "112575": [95, 96, 97],
    "112576": [125, 126, 127, 128],
    "112577": [232, 233, 234, 235],
    "119763": [48, 49, 50, 51, 52, 53, 54],
    "119764": [116, 117, 118, 119, 120, 121, 122],
    "119948": [429, 430, 431, 432, 433],
    "124830": [47, 48, 49, 50],
    "124831": [144, 145, 146, 147],
    "102441": [9, 10, 11, 12, 13, 14, 15, 16],
    "102444": [725, 726, 727, 728, 729, 730, 731, 732],
    "102445": [61, 62, 63, 64, 65, 66, 67, 68],
    "102450": [8, 9, 10, 11, 12, 13, 14, 15]
}
```

**Comment by AlonEirew** [comment]
Hi @mbugert, 
Thank you for letting me know! and also for sending the repaired tokens. 
I will update once fixed.

**Comment by AlonEirew** [comment]
Hi @mbugert, I've fixed the issue, fix was needed only in files, code for generation WEC was find (issue was due to python conversion for "event-coref" project and using a different python tokenizer).

Thanks again for opening this issue.
