### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by gaoqiang-3416** [AlonEirew/extract-wec#5]
![image](https://user-images.githubusercontent.com/55910045/229955782-b4a19bd1-8084-4037-b47b-787051ed19c7.png)
can you tell me what is this file,what is this file used for ?and how can i get this file?thank you

**Comment by AlonEirew** [comment]
This is the location where the [h2 dataset](https://www.h2database.com/html/main.html) will be created and saved (on your machine).
