### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by cooper12121** [AlonEirew/extract-wec#6]
![image](https://user-images.githubusercontent.com/55910045/229964843-59c26e36-9bb8-407a-b4db-8a75b103369b.png)
when i run this command ,i met this problem ,i have try many methods but it still exits,can you help me,thank you

**Comment by gaoqiang-3416** [comment]
![image](https://user-images.githubusercontent.com/55910045/229973205-b4c9fe0d-9b77-49c4-8ee6-d70e7dac46b0.png)
can you tell me where is lib folder comes from?

**Comment by AlonEirew** [comment]
Hi @gaoqiang-3416,

Yes this doesn't work anymore, unfortunately I don't have time to fix it and I'll remove it from the readme file.
A workaround can be to run the script from an IDE (intellij / VSCode / etc...).

**Comment by gaoqiang-3416** [comment]
> Hi @gaoqiang-3416,
> 
> Yes this doesn't work anymore, unfortunately I don't have time to fix it and I'll remove it from the readme file. A workaround can be to run the script from an IDE (intellij / VSCode / etc...).

so which script should i run,
this #>java -Xmx90000m -DentityExpansionLimit=2147480000 -DtotalEntitySizeLimit=2147480000 -Djdk.xml.totalEntitySizeLimit=2147480000 -cp "lib/*" scripts.ExtractInfoboxs
or just the ExtractInfoboxs.java file ,there exits problems when run the java file

**Comment by AlonEirew** [comment]
If you are running from an IDE (as a Gradle project), all dependencies should be part of the project.

For other cases, such as running from command line, I've updated the instructions in the project README file [here](https://github.com/AlonEirew/extract-wec#language-adaptation).
Let me know if this now works for you.

**Comment by gaoqiang-3416** [comment]
> The problem seems related to the Elasticsearch API, a couple of questions:
> 
> 1. Did you generate the ElasticSearch index using the instructions in [wikipedia-to-elastic](https://github.com/AlonEirew/wikipedia-to-elastic) project?
> 2. Did you verify that the ElasticSearch server is running and able to accept requests?

![image](https://user-images.githubusercontent.com/55910045/231753276-52330acc-cae4-49c7-a9a6-e913072e743d.png)
yeal,the elasticsearch server can return result,i mean in your code ,the Configuration class first need to init,but in your ElasticQueryApi.java file your Configuration class didn't init,it's a null pointer
![image](https://user-images.githubusercontent.com/55910045/231754264-fd7c456d-bcca-409c-aaa8-89d112e8d292.png)
![image](https://user-images.githubusercontent.com/55910045/231754372-48f6f5f3-79cb-4a81-9c19-4b1f686e5cce.png)
![image](https://user-images.githubusercontent.com/55910045/231754431-706b7769-ee98-46f4-a527-7a6bfdaafaf7.png)

when i try to init the Configuration,the Environment injected by myself has problems,so can you fix it?

**Comment by AlonEirew** [comment]
Ok, I've just pushed an update to the code and readme file. 
Notice that the way you should run the script have changed (**see in [readme](https://github.com/AlonEirew/extract-wec#language-adaptation)**)
let me know if this get you further
